document.write("EXTERNAL JAVA DOCUMENT WRITEJAVA SCRIPT");
window.alert("EXTERNAL JAVA ALERT JAVA SCRIPT");
console.log("EXTERNAL JAVA CONSOLE LOG JAVA SCRIPT");
console.log("EXTERNAL JAVA HOW ARE YOU");